# prod
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubrix-johnny-be-good-prod"
  description: "kubrix-johnny-be-good-prod"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: http://kubrix-johnny-be-good-prod.kubrix.stackit.run
      title: Prod Instance of kubrix-johnny-be-good
      icon: web
  annotations:
    github.com/project-slug: kubriX-stackit-demo/kubrix-johnny-be-good
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=johnny-be-good-prod'
    argocd/app-namespace: adn-kubrix
    argocd/app-name: johnny-be-good-prod
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.kubrix.stackit.run/project/kubrix-johnny-be-good-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.kubrix.stackit.run/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=kubrix-demo&var-namespace=kubrix-johnny-be-good-prod&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: prod
  owner: "kubrix"
  system: johnny-be-good
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: kubrix-johnny-be-good
---
#qa
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubrix-johnny-be-good-qa"
  description: "kubrix-johnny-be-good-qa"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: http://kubrix-johnny-be-good-qa.kubrix.stackit.run
      title: QA Instance of kubrix-johnny-be-good
      icon: web
  annotations:
    github.com/project-slug: kubriX-stackit-demo/kubrix-johnny-be-good
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=johnny-be-good-qa'
    argocd/app-namespace: adn-kubrix
    argocd/app-name: johnny-be-good-qa
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.kubrix.stackit.run/project/kubrix-johnny-be-good-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.kubrix.stackit.run/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=kubrix-demo&var-namespace=kubrix-johnny-be-good-qa&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: qa
  owner: "kubrix"
  system: johnny-be-good
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: kubrix-johnny-be-good
---
# test
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubrix-johnny-be-good-test"
  description: "kubrix-johnny-be-good-test"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: http://kubrix-johnny-be-good-test.kubrix.stackit.run
      title: Test Instance of kubrix-johnny-be-good
      icon: web
  annotations:
    github.com/project-slug: kubriX-stackit-demo/kubrix-johnny-be-good
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=johnny-be-good-test'
    argocd/app-namespace: adn-kubrix
    argocd/app-name: johnny-be-good-test
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.kubrix.stackit.run/project/kubrix-johnny-be-good-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.kubrix.stackit.run/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=kubrix-demo&var-namespace=kubrix-johnny-be-good-test&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: test
  owner: "kubrix"
  system: johnny-be-good
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: kubrix-johnny-be-good
---
# main, at the end of catalog-info.yaml so that register link is on main component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubrix-johnny-be-good"
  description: "kubrix-johnny-be-good"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: https://argocd.kubrix.stackit.run/applications/adn-kubrix/kubrix-johnny-be-good?resource=
      title: ArgoCD Application Information of kubrix-johnny-be-good
      icon: web
  annotations:
    github.com/project-slug: kubriX-stackit-demo/kubrix-johnny-be-good
    argocd/app-namespace: adn-kubrix
    argocd/app-name: kubrix-johnny-be-good
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.kubrix.stackit.run/project/kubrix-johnny-be-good-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
spec:
  type: service
  lifecycle: experimental
  owner: "kubrix"
  system: johnny-be-good
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
---